pipeline {
    agent any
    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select the environment to deploy')
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    // Securely bind credentials
                    withCredentials([[
                        $class: 'UsernamePasswordMultiBinding',
                        credentialsId: 'aws_credentials',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        // Initialize Terraform
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Select Workspace') {
            steps {
                script {
                    // Select or create Terraform workspace based on the provided parameter
                    sh "terraform workspace select ${params.ENV} || terraform workspace new ${params.ENV}"
                }
            }
        }
        stage('Apply') {
            steps {
                script {
                    // Securely bind credentials again for the apply stage
                    withCredentials([[
                        $class: 'UsernamePasswordMultiBinding',
                        credentialsId: 'aws_credentials',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        // Apply Terraform configuration using the appropriate tfvars file for the environment
                        sh "terraform apply -auto-approve --var-file ${params.ENV}.tfvars"
                    }
                }
            }
        }
    }
}

